"""Migration

Revision ID: 037bfe69c0e9
Revises: 6a653b4d75d8
Create Date: 2024-11-11 15:14:58.957751

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '037bfe69c0e9'
down_revision = '6a653b4d75d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
