"""Migration

Revision ID: 040a9c6cd751
Revises: ebe2cff6bc18
Create Date: 2024-11-12 18:43:43.491802

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '040a9c6cd751'
down_revision = 'ebe2cff6bc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
