"""Migration

Revision ID: 0f8b57b44ac9
Revises: b475f7f34959
Create Date: 2024-11-12 17:14:24.250306

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0f8b57b44ac9'
down_revision = 'b475f7f34959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
