"""Migration

Revision ID: 21fe7f77f07e
Revises: 037bfe69c0e9
Create Date: 2024-11-11 16:21:42.767932

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '21fe7f77f07e'
down_revision = '037bfe69c0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
