"""Migration

Revision ID: 2993d8fb1496
Revises: 3b63fb062b81
Create Date: 2024-11-11 15:53:57.894233

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2993d8fb1496'
down_revision = '3b63fb062b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
