"""Migration

Revision ID: 3b63fb062b81
Revises: 4e37c6b58703
Create Date: 2024-11-11 15:28:11.543997

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3b63fb062b81'
down_revision = '4e37c6b58703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
