"""Migration

Revision ID: 4e73029d42a7
Revises: b10f69d350ba
Create Date: 2024-11-11 20:20:02.379184

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4e73029d42a7'
down_revision = 'b10f69d350ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
