"""Migration

Revision ID: 53784b33cc21
Revises: 4e73029d42a7
Create Date: 2024-11-12 14:53:40.400673

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '53784b33cc21'
down_revision = '4e73029d42a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
