"""Migration

Revision ID: 544a3db39567
Revises: dd3361d6eb5d
Create Date: 2024-11-11 15:03:55.842527

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '544a3db39567'
down_revision = 'dd3361d6eb5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
