"""Migration

Revision ID: 59d96c95882d
Revises: eb3865da422c
Create Date: 2024-11-12 16:03:29.399843

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '59d96c95882d'
down_revision = 'eb3865da422c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
