"""Migration

Revision ID: 60ec6c142c36
Revises: 040a9c6cd751
Create Date: 2024-11-12 18:46:44.615694

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '60ec6c142c36'
down_revision = '040a9c6cd751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
