"""Migration

Revision ID: 6a653b4d75d8
Revises: 408d4f0b7290
Create Date: 2024-11-11 13:34:51.372550

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6a653b4d75d8'
down_revision = '408d4f0b7290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
