"""Migration

Revision ID: 82167b9b17ee
Revises: 9301fa8f8d84
Create Date: 2024-11-11 16:13:37.405080

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '82167b9b17ee'
down_revision = '9301fa8f8d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
