"""Migration

Revision ID: 9301fa8f8d84
Revises: 2993d8fb1496
Create Date: 2024-11-11 16:07:47.960496

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9301fa8f8d84'
down_revision = '2993d8fb1496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
