"""Migration

Revision ID: b475f7f34959
Revises: b8ebb334f434
Create Date: 2024-11-12 17:05:30.017739

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b475f7f34959'
down_revision = 'b8ebb334f434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
