"""Migration

Revision ID: c0cb60b039a8
Revises: 0d6270e9b594
Create Date: 2024-11-11 19:52:59.921140

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c0cb60b039a8'
down_revision = '0d6270e9b594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
