"""Migration

Revision ID: d5207a26abe2
Revises: 0f8b57b44ac9
Create Date: 2024-11-12 17:56:08.950947

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd5207a26abe2'
down_revision = '0f8b57b44ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
