"""Migration

Revision ID: dd3361d6eb5d
Revises: 03535c4b1121
Create Date: 2024-11-11 15:00:35.872421

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dd3361d6eb5d'
down_revision = '03535c4b1121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
