"""Migration

Revision ID: ebe2cff6bc18
Revises: d64aea282328
Create Date: 2024-11-12 18:36:20.142582

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ebe2cff6bc18'
down_revision = 'd64aea282328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
