"""Initial migration

Revision ID: 33ba4df336d9
Revises: b91e85583261
Create Date: 2024-11-04 15:18:39.146196

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '33ba4df336d9'
down_revision = 'b91e85583261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.drop_column('room', 'room_number')
    op.alter_column('user', 'role_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('room', sa.Column('room_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('room', 'number')
    # ### end Alembic commands ###
