"""migrations

Revision ID: 5f1f2a9db25d
Revises: 1664bc045f99
Create Date: 2024-10-17 18:29:09.025713

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5f1f2a9db25d'
down_revision = '1664bc045f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
