"""Initial migration

Revision ID: 8d5a1ad8eccc
Revises: 55c856c0253d
Create Date: 2024-11-04 15:36:08.219769

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8d5a1ad8eccc'
down_revision = '55c856c0253d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
