"""added Subject model

Revision ID: 9b1a3970e6ca
Revises: c66ec4b05231
Create Date: 2024-10-22 15:59:12.576365

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9b1a3970e6ca'
down_revision = 'c66ec4b05231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('class', sa.Column('subject_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'class', 'subject', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class', type_='foreignkey')
    op.drop_column('class', 'subject_id')
    op.drop_table('subject')
    # ### end Alembic commands ###
