"""added back relationships

Revision ID: b91e85583261
Revises: d1c7a6886679
Create Date: 2024-10-22 16:42:21.643716

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b91e85583261'
down_revision = 'd1c7a6886679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('room_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'class', 'room', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class', type_='foreignkey')
    op.drop_column('class', 'room_id')
    # ### end Alembic commands ###
