"""added Review model

Revision ID: d1c7a6886679
Revises: 98446dbf1c00
Create Date: 2024-10-22 16:06:31.978773

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd1c7a6886679'
down_revision = '98446dbf1c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('teaching_quality', sa.Integer(), nullable=False),
    sa.Column('material_clarity', sa.Integer(), nullable=False),
    sa.Column('event_quality', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
